### ISSUE TITLE
Doesn't work when paired with FSP

### ISSUE THREAD

**Issue by VFDan** [tomysshadow/OldCPUSimulator#1]
When OldCPUSimulator is linked to a Flashpoint Secure Player starting .bat file, it doesn't affect the program started by that .bat file.

**Comment by VFDan** [comment]
nosamu just pointed me to the FSP documentation; this should be at least pointed to in the README.

**Comment by tomysshadow** [comment]
Old CPU Simulator was not written specifically for use with Flashpoint. It
is a general purpose application for underclocking software. It predates
the Flashpoint Secure Player and it is not "aware" of what the Flashpoint
Secure Player is doing.

FSP is designed such that it should work either way: with the Old CPU
Simulator started first, or with it set in the configuration file. Look at
FPSoftware\startSVR.bat in Flashpoint for an example of the former - in
that case the Old CPU Simulator is started first. Hypercosm is an example
of the latter: Old CPU Simulator is started via its configuration file.
Both will work nearly identically to each other, although if Old CPU
Simulator is started via the batch script, then the settings specified
there are preferred by the player.

**Comment by VFDan** [comment]
Alright, I'll close this issue then, it was just for a README change that I should've found in the other docs anyway :/
Also, thanks for mentioning what startSVR.bat does, I was looking for a way for variable speed, I can probably work with that.
