### ISSUE TITLE
Thank you very much!

### ISSUE THREAD

**Issue by BJNFNE** [tomysshadow/OldCPUSimulator#2]
- This is not an Issue.
I wanna thank you so much, i have an game that i played in my Childhood called: Adibou & Paziral's Secret.
and due to modern Machines it was way to fast. but thanks to your Program its now working fine :) 💯

**Comment by tomysshadow** [comment]
Appreciate it! I'm curious how you heard about my tool - I haven't promoted
it very heavily. I have a new version coming out soon with some minor
improvements.

**Comment by BJNFNE** [comment]
@tomysshadow i searched for how i can make an tool myself to limit the CPU speed in C# then Google shows me your Github Repository of OCS.

**Comment by BJNFNE** [comment]
@tomysshadow if you want i can help you by adding Multi Language.

**Comment by tomysshadow** [comment]
I haven't really made an effort to internationalize the code for this, but
you can try if you want. The solution consists of two projects: the command
line tool, which is written in C++ and is the main brain of the operation,
and the GUI, which is written in C# with WinForms and just wraps the
command line tool. In it's entirety it isn't a very large project so you
could probably become familiar with how it works fairly quickly. The GUI
uses a resources file for error messages, so those would be easy to
substitute, but not the main form itself as-is.
